### ISSUE TITLE
autojump-rs is slower

### ISSUE THREAD

**Issue by skywind3000** [xen0n/autojump-rs#12]
autojump-rs is slower than [z.lua](https://github.com/skywind3000/z.lua), autojump-rs takes 0.050s to change directory while z.lua only needs 0.017s.

**Comment by xen0n** [comment]
wtf ppl did the actual benchmarks

will do a profile later and btw Happy Chinese New Year my fellow  ;-)

**Comment by xen0n** [comment]
In the meantime, could you provide your benchmarking environment setup (i.e. arch, OS, compile-time options etc.) and methodology please? This can be very important when debugging perf problems as frequently there's no actual problem in the first place, rather people doing the wrong things.

**Comment by skywind3000** [comment]
Debian 9, installation instructions:

    cargo install autojump

then executable `autojump` can be found in $HOME/.cargo/bin.  

benchmark (bash) after sourcing `$HOME/.autojump/share/autojump/autojump.bash`:

original aotujump (python version):

```bash
skywind@weilin0:~/.vim$ time j vim
/home/skywind/software/vim

real    0m0.149s
user    0m0.047s
sys     0m0.063s
```

switch to autojump-rs:

```bash
skywind@weilin0:~/software/vim$ export PATH=/home/skywind/.cargo/bin:$PATH
skywind@weilin0:~/software/vim$ time j vim
/home/skywind/.vim

real    0m0.075s
user    0m0.000s
sys     0m0.031s
```

use z.lua:

```bash
skywind@weilin0:~/.vim$ time z vim

real    0m0.019s
user    0m0.016s
sys     0m0.016s
```

**Comment by Congee** [comment]
Glad to see you guys improve programmers' life

**Comment by xen0n** [comment]
0.4.0 is out, major startup bottleneck was `docopt` which was removed. It had to parse a whole docstring before it can even start processing `argv`. Now the performance should be on parity with any sanely written tool out there.
