### ISSUE TITLE
[Request] Release binaries for aarch64-linux-android

### ISSUE THREAD

**Issue by bharatvaj** [xen0n/autojump-rs#124]
Hi, thanks for autojump-rs! Can you provide a package for aarch64-linux-android. Navigating with 'j' will be really useful in termux.

**Comment by xen0n** [comment]
Binaries for version 0.5.1 are now available which contains `aarch64-linux-android`. Please check it out and report back if anything not working!

**Comment by bharatvaj** [comment]
Whoa man thanks, that's really cool.  Works as intended on termux.
