### ISSUE TITLE
Missing x86-64 glibc linux binary

### ISSUE THREAD

**Issue by HollMax** [xen0n/autojump-rs#13]
Am I missing something, or is there no x86-64-linux-gnu pre-built binary available?
I'd assume that to be the most used target, yet I can't find it in downloads.

**Comment by xen0n** [comment]
Just use the `x86_64-unknown-linux-musl` binary. It's statically linked so none of the dynamic linking startup overhead. The overhead is slight but measurable so I just made that choice for you 😄
