### ISSUE TITLE
[Release] Missing binaries for 0.5.0 release

### ISSUE THREAD

**Issue by tech189** [xen0n/autojump-rs#201]
Hi, could you please upload the compiled binaries for the latest release, 0.5.0? Thanks!

**Comment by smlavine** [comment]
Hello,

I would appreciate it if this could be done too, please. Otherwise I will need to modify the PKGBUILD for the AUR distribution of the program. If it can't be done, no biggie, but please let us know. Happy New Year!

**Comment by xen0n** [comment]
Hi @tech189 @smlavine, sorry for the late fix! It was an error in the deploy workflow's tag matching condition that excluded our tags from being built.

Version 0.5.1 is now out and contains the binaries as expected, please test, thanks!

**Comment by smlavine** [comment]
Binaries seem to work for 0.5.1, thank you!

**Comment by tech189** [comment]
Perfect, thank you!
