### ISSUE TITLE
Autojump subdirectory when XDG_DATA_HOME is specified does not behave properly

### ISSUE THREAD

**Issue by ynavott** [xen0n/autojump-rs#36]
An issue regarding this bug (#14) was already submitted and allegedly fixed, but I am currently experiencing similar behaviour: 

When XDG_DATA_HOME isn't specified, the directory inside ``~/.local/share`` is created, but when the variable is specified to be ``~/.local/share`` (in ``~/.zshenv`` for example) the subdirectory is created but autojump does not write the database inside it, but in ``~/.local/share``.

When there is an already existing subdirectory autojump fails to recognize the already existing database inside it and proceeds to create a new database outside the subdirectory.

**Comment by xen0n** [comment]
Ah, looking at the latest released version I think maybe I'll have to put up a new release. That fix might not be included in the version most people use.

**Comment by xen0n** [comment]
The holiday is now over in China, I'll have to take care of this in a week or so. Hopefully I don't forget!

**Comment by ynavott** [comment]
I was just about to write that I have just realised that the binary I was using is from July 2019, and does not have the fix included in it. I'd love to know how to build a binary from the source myself to save me the wait for official releases, though it is unclear to me how I am supposed to build a binary from source locally, since I am not very familiar with rust and ``cargo build`` does not create a binary, so some guidance and maybe an addition to the documentation afterwards would be highly appreciated. Using Manjaro Linux.

**Comment by xen0n** [comment]
Hmmm that's strange if `cargo build` doesn't correctly build the app. Look at `target/debug` to find `autojump` inside it. (BTW you really want `cargo build --release` for a much snappier binary.)

**Comment by ynavott** [comment]
Nevermind, it did actually make a binary, for some reason it has a different icon in my file explorer compared to the github binary but it is 100% functional, it was just in ``target/release`` the whole time. Thanks for the help!
 
I guess you can close this now since there is no actual bug in the updated code.
