### ISSUE TITLE
Batch files for Windows usage

### ISSUE THREAD

**Issue by tomv564** [xen0n/autojump-rs#4]
I can confirm that autojump-rs works great with Windows (using clink), but it is not totally a drop-in replacement.

I have modified the batch files to remove the python invocation at https://github.com/tomv564/windows-env/tree/master/autojump, did you want to distribute/document this with autojump-rs?

**Comment by xen0n** [comment]
Hmm, previously I planned to do that but failed to allocate time. Now that there is #5 which requires some free time anyway, to make the project more useful I think I'll do this too.
