### ISSUE TITLE
Fix oh-my-zsh integration

### ISSUE THREAD

**Issue by dunmatt** [xen0n/autojump-rs#44]
Currently, if you manually edit oh-my-zsh's autojump plugin to point to this autojump it dies pretty horribly:

    ➜ zsh
    [8] 44848
    /Users/mdunlap/.cargo/bin/autojump:1: command not found: ^C
    /Users/mdunlap/.cargo/bin/autojump:3: parse error near `)'
    /Users/mdunlap/.cargo/bin/autojump:1: parse error in command substitution
    [8]  + 44848 exit 127    >
    /Users/mdunlap/.cargo/bin/autojump:7: command not found: H\M-\t}\M-xH\M-\tu\M-pH\M-^ME\M-xH\M-\tE\M-PH\M-^M^E\M-^A\M-U^E
    /Users/mdunlap/.cargo/bin/autojump:7: no matches found: M\M-\tn^HI\M-\t^^PH\M-^C\M-D^H[AA]A^A_]þ^A^@^@^@H\M-\t\M-_\M-h0\M-u\M-^?\M-^?\M->^A^@^@^@L\M-\t\M-o\M-h#\M-u\M-^?\M-^?^O^_^@UH\M-\t\M-eH\M-^C\M-lH\M-\t}\M-xH\M-\tu\M-pH\M-^ME\M-xH\M-\tE\M-PH\M-^M^E^Q\M-U^E^@H\M-\tE\M-XH\M-^MM\M-pH\M-\tM\M-`H\M-\tE\M-hH\M-^M^E

Shell integration is a pretty strong argument in favor of the Python version, at least for me.  Do you have an estimate of how hard this would be to fix?  I could probably spare some cycles to scratch my own itch if you think it's something a newcomer could handle fixing.

**Comment by xen0n** [comment]
Hi, this piece of error message clearly has some garbled contents, I'm confident that your shell is trying to execute the binary as script.

Could you provide your modified version of autojump plugin for troubleshooting? IIRC the plugin doesn't overwrite PATH, so as long as `autojump-rs` exists as `autojump` and before the vanilla `autojump` it should automatically take over.

**Comment by dunmatt** [comment]
Ah, right you are.  I had just blindly prepended the path to `autojump-rs` to the `autojump_paths` list, not noticing that everything else on that list was a shell script.  I hadn't realized that I'd need the python version installed in order for the rust version to integrate with zsh.  But now that I've installed it all seems to be well, thanks for spotting my error!
