### ISSUE TITLE
binary releases

### ISSUE THREAD

**Issue by untoreh** [xen0n/autojump-rs#5]
provide binary releases
also the nightly channel is needed

**Comment by xen0n** [comment]
Ah, now that there're *others* depending on this, maybe I will do that this weekend...

**Comment by theduke** [comment]
Yes please, really would love to switch from autojump to something less pythonic. ;)

**Comment by xen0n** [comment]
Quick note:

The "0.2.2" release is problematic (`atomicwrites` hasn't been updated in a year and its outdated `nix` dep has already blocked deploy by failing over 1/2 of cross-compiled arches...), hence not tagged. I'll likely investigate the `jc` bug before force-pushing a 0.3 and making the "0.2.2 release branch" disappear.

**Comment by theduke** [comment]
@xen0n I looked at the code.

What do you think about making autojump-rs compile on stable?
That would make a few things easier.

Nightly is only needed for two spots where an iterator is returned with impl trait. 

The code is very elegant, but could be replaced with either of: writing custom iterator implementation, returned a boxed iterator or restructuring the code a bit.

**Comment by xen0n** [comment]
@theduke Hmm, when I first wrote the code I'm not too familiar with Rust, and to get back some of my Python nostalgia, I chose to translate the iterators in the most "native" or Pythonic way. XD

I think I'd try to do that as part of the proper 0.3 release, some Windows fixes are needed anyway, so it wouldn't harm. 😂

**Comment by xen0n** [comment]
0.3.0 is out with all the binaries! I'm closing this now... feel free to open issues in case some of the binaries don't work for you!
